package ${package};

import ${typeName};
import ${exampleJavaName};
import com.nbm.waf.core.modeldriven.Mapper;

/**
 * auto generated by nbm-dbgenerator at ${.now}
 */
public interface ${typeSimpleName}Mapper extends Mapper<${typeSimpleName}, ${typeSimpleName}Example>
{
}