package com.nbm.core.modeldriven.test.model.dao;

import com.nbm.core.modeldriven.test.model.ModelDrivenTestModel;
import com.nbm.core.modeldriven.test.model.dao.ModelDrivenTestModelExample;
import com.nbm.waf.core.modeldriven.Mapper;

/**
 * auto generated by nbm-dbgenerator at Jan 19, 2017 4:36:05 PM
 */
public interface ModelDrivenTestModelMapper extends Mapper<ModelDrivenTestModel, ModelDrivenTestModelExample>
{
}