package com.nbm.core.modeldriven.test.model.dao;

import java.util.ArrayList;
import java.util.List;

import com.nbm.core.modeldriven.enums.YesOrNo;
import java.util.Date;

/**
 * auto generated by nbm-dbgenerator at 2016-5-11 10:20:49
 */
public class ModelDrivenTestModelExample
{
        protected String orderByClause;

        protected boolean distinct;

        protected List<Criteria> oredCriteria;

        public ModelDrivenTestModelExample()
        {
                oredCriteria = new ArrayList<Criteria>();
        }

        public void setOrderByClause(String orderByClause)
        {
                this.orderByClause = orderByClause;
        }

        public String getOrderByClause()
        {
                return orderByClause;
        }

        public void setDistinct(boolean distinct)
        {
                this.distinct = distinct;
        }

        public boolean isDistinct()
        {
                return distinct;
        }

        public List<Criteria> getOredCriteria()
        {
                return oredCriteria;
        }

        public void or(Criteria criteria)
        {
                oredCriteria.add(criteria);
        }

        public Criteria or()
        {
                Criteria criteria = createCriteriaInternal();
                oredCriteria.add(criteria);
                return criteria;
        }

        public Criteria createCriteria()
        {
                Criteria criteria = createCriteriaInternal();
                if (oredCriteria.size() == 0)
                {
                        oredCriteria.add(criteria);
                }
                return criteria;
        }

        protected Criteria createCriteriaInternal()
        {
                Criteria criteria = new Criteria();
                return criteria;
        }

        public void clear()
        {
                oredCriteria.clear();
                orderByClause = null;
                distinct = false;
        }

        protected abstract static class GeneratedCriteria
        {
                protected List<Criterion> criteria;

                protected GeneratedCriteria()
                {
                        super();
                        criteria = new ArrayList<Criterion>();
                }

                public boolean isValid()
                {
                        return criteria.size() > 0;
                }

                public List<Criterion> getAllCriteria()
                {
                        return criteria;
                }

                public List<Criterion> getCriteria()
                {
                        return criteria;
                }

                protected void addCriterion(String condition)
                {
                        if (condition == null)
                        {
                                throw new RuntimeException("Value for condition cannot be null");
                        }
                        criteria.add(new Criterion(condition));
                }

                protected void addCriterion(String condition, Object value, String property)
                {
                        if (value == null)
                        {
                                throw new RuntimeException("Value for " + property
                                                + " cannot be null");
                        }
                        criteria.add(new Criterion(condition, value));
                }

                protected void addCriterion(String condition,
                                Object value1,
                                Object value2,
                                String property)
                {
                        if (value1 == null || value2 == null)
                        {
                                throw new RuntimeException("Between values for " + property
                                                + " cannot be null");
                        }
                        criteria.add(new Criterion(condition, value1, value2));
                }

				public Criteria andIdIsNull()
                {
                        addCriterion("ID is null");
                        return (Criteria) this;
                }

                public Criteria andIdIsNotNull()
                {
                        addCriterion("ID is not null");
                        return (Criteria) this;
                }

                public Criteria andIdEqualTo(Long value)
                {
                        addCriterion("ID =", value, "id");
                        return (Criteria) this;
                }

                public Criteria andIdNotEqualTo(Long value)
                {
                        addCriterion("ID <>", value, "id");
                        return (Criteria) this;
                }

                public Criteria andIdGreaterThan(Long value)
                {
                        addCriterion("ID >", value, "id");
                        return (Criteria) this;
                }

                public Criteria andIdGreaterThanOrEqualTo(Long value)
                {
                        addCriterion("ID >=", value, "id");
                        return (Criteria) this;
                }

                public Criteria andIdLessThan(Long value)
                {
                        addCriterion("ID <", value, "id");
                        return (Criteria) this;
                }

                public Criteria andIdLessThanOrEqualTo(Long value)
                {
                        addCriterion("ID <=", value, "id");
                        return (Criteria) this;
                }
                

                public Criteria andIdIn(List<Long> values)
                {
                        addCriterion("ID in", values, "id");
                        return (Criteria) this;
                }

                public Criteria andIdNotIn(List<Long> values)
                {
                        addCriterion("ID not in", values, "id");
                        return (Criteria) this;
                }

                public Criteria andIdBetween(Long value1, Long value2)
                {
                        addCriterion("ID between", value1, value2, "id");
                        return (Criteria) this;
                }

                public Criteria andIdNotBetween(Long value1, Long value2)
                {
                        addCriterion("ID not between", value1, value2, "id");
                        return (Criteria) this;
                }
				public Criteria andNameIsNull()
                {
                        addCriterion("NAME is null");
                        return (Criteria) this;
                }

                public Criteria andNameIsNotNull()
                {
                        addCriterion("NAME is not null");
                        return (Criteria) this;
                }

                public Criteria andNameEqualTo(String value)
                {
                        addCriterion("NAME =", value, "name");
                        return (Criteria) this;
                }

                public Criteria andNameNotEqualTo(String value)
                {
                        addCriterion("NAME <>", value, "name");
                        return (Criteria) this;
                }

                public Criteria andNameGreaterThan(String value)
                {
                        addCriterion("NAME >", value, "name");
                        return (Criteria) this;
                }

                public Criteria andNameGreaterThanOrEqualTo(String value)
                {
                        addCriterion("NAME >=", value, "name");
                        return (Criteria) this;
                }

                public Criteria andNameLessThan(String value)
                {
                        addCriterion("NAME <", value, "name");
                        return (Criteria) this;
                }

                public Criteria andNameLessThanOrEqualTo(String value)
                {
                        addCriterion("NAME <=", value, "name");
                        return (Criteria) this;
                }
                
                public Criteria andNameLike(String value) 
                {
                        addCriterion("NAME like", value, "name");
                        return (Criteria) this;
                }

                public Criteria andNameNotLike(String value)
                {
                        addCriterion("NAME not like", value, "name");
                        return (Criteria) this;
                }

                public Criteria andNameIn(List<String> values)
                {
                        addCriterion("NAME in", values, "name");
                        return (Criteria) this;
                }

                public Criteria andNameNotIn(List<String> values)
                {
                        addCriterion("NAME not in", values, "name");
                        return (Criteria) this;
                }

                public Criteria andNameBetween(String value1, String value2)
                {
                        addCriterion("NAME between", value1, value2, "name");
                        return (Criteria) this;
                }

                public Criteria andNameNotBetween(String value1, String value2)
                {
                        addCriterion("NAME not between", value1, value2, "name");
                        return (Criteria) this;
                }
				public Criteria andRemarkIsNull()
                {
                        addCriterion("REMARK is null");
                        return (Criteria) this;
                }

                public Criteria andRemarkIsNotNull()
                {
                        addCriterion("REMARK is not null");
                        return (Criteria) this;
                }

                public Criteria andRemarkEqualTo(String value)
                {
                        addCriterion("REMARK =", value, "remark");
                        return (Criteria) this;
                }

                public Criteria andRemarkNotEqualTo(String value)
                {
                        addCriterion("REMARK <>", value, "remark");
                        return (Criteria) this;
                }

                public Criteria andRemarkGreaterThan(String value)
                {
                        addCriterion("REMARK >", value, "remark");
                        return (Criteria) this;
                }

                public Criteria andRemarkGreaterThanOrEqualTo(String value)
                {
                        addCriterion("REMARK >=", value, "remark");
                        return (Criteria) this;
                }

                public Criteria andRemarkLessThan(String value)
                {
                        addCriterion("REMARK <", value, "remark");
                        return (Criteria) this;
                }

                public Criteria andRemarkLessThanOrEqualTo(String value)
                {
                        addCriterion("REMARK <=", value, "remark");
                        return (Criteria) this;
                }
                
                public Criteria andRemarkLike(String value) 
                {
                        addCriterion("REMARK like", value, "remark");
                        return (Criteria) this;
                }

                public Criteria andRemarkNotLike(String value)
                {
                        addCriterion("REMARK not like", value, "remark");
                        return (Criteria) this;
                }

                public Criteria andRemarkIn(List<String> values)
                {
                        addCriterion("REMARK in", values, "remark");
                        return (Criteria) this;
                }

                public Criteria andRemarkNotIn(List<String> values)
                {
                        addCriterion("REMARK not in", values, "remark");
                        return (Criteria) this;
                }

                public Criteria andRemarkBetween(String value1, String value2)
                {
                        addCriterion("REMARK between", value1, value2, "remark");
                        return (Criteria) this;
                }

                public Criteria andRemarkNotBetween(String value1, String value2)
                {
                        addCriterion("REMARK not between", value1, value2, "remark");
                        return (Criteria) this;
                }
				public Criteria andModelLastUpdateTimeIsNull()
                {
                        addCriterion("MODEL_LAST_UPDATE_TIME is null");
                        return (Criteria) this;
                }

                public Criteria andModelLastUpdateTimeIsNotNull()
                {
                        addCriterion("MODEL_LAST_UPDATE_TIME is not null");
                        return (Criteria) this;
                }

                public Criteria andModelLastUpdateTimeEqualTo(Date value)
                {
                        addCriterion("MODEL_LAST_UPDATE_TIME =", value, "modelLastUpdateTime");
                        return (Criteria) this;
                }

                public Criteria andModelLastUpdateTimeNotEqualTo(Date value)
                {
                        addCriterion("MODEL_LAST_UPDATE_TIME <>", value, "modelLastUpdateTime");
                        return (Criteria) this;
                }

                public Criteria andModelLastUpdateTimeGreaterThan(Date value)
                {
                        addCriterion("MODEL_LAST_UPDATE_TIME >", value, "modelLastUpdateTime");
                        return (Criteria) this;
                }

                public Criteria andModelLastUpdateTimeGreaterThanOrEqualTo(Date value)
                {
                        addCriterion("MODEL_LAST_UPDATE_TIME >=", value, "modelLastUpdateTime");
                        return (Criteria) this;
                }

                public Criteria andModelLastUpdateTimeLessThan(Date value)
                {
                        addCriterion("MODEL_LAST_UPDATE_TIME <", value, "modelLastUpdateTime");
                        return (Criteria) this;
                }

                public Criteria andModelLastUpdateTimeLessThanOrEqualTo(Date value)
                {
                        addCriterion("MODEL_LAST_UPDATE_TIME <=", value, "modelLastUpdateTime");
                        return (Criteria) this;
                }
                

                public Criteria andModelLastUpdateTimeIn(List<Date> values)
                {
                        addCriterion("MODEL_LAST_UPDATE_TIME in", values, "modelLastUpdateTime");
                        return (Criteria) this;
                }

                public Criteria andModelLastUpdateTimeNotIn(List<Date> values)
                {
                        addCriterion("MODEL_LAST_UPDATE_TIME not in", values, "modelLastUpdateTime");
                        return (Criteria) this;
                }

                public Criteria andModelLastUpdateTimeBetween(Date value1, Date value2)
                {
                        addCriterion("MODEL_LAST_UPDATE_TIME between", value1, value2, "modelLastUpdateTime");
                        return (Criteria) this;
                }

                public Criteria andModelLastUpdateTimeNotBetween(Date value1, Date value2)
                {
                        addCriterion("MODEL_LAST_UPDATE_TIME not between", value1, value2, "modelLastUpdateTime");
                        return (Criteria) this;
                }
				public Criteria andModelCreateTimeIsNull()
                {
                        addCriterion("MODEL_CREATE_TIME is null");
                        return (Criteria) this;
                }

                public Criteria andModelCreateTimeIsNotNull()
                {
                        addCriterion("MODEL_CREATE_TIME is not null");
                        return (Criteria) this;
                }

                public Criteria andModelCreateTimeEqualTo(Date value)
                {
                        addCriterion("MODEL_CREATE_TIME =", value, "modelCreateTime");
                        return (Criteria) this;
                }

                public Criteria andModelCreateTimeNotEqualTo(Date value)
                {
                        addCriterion("MODEL_CREATE_TIME <>", value, "modelCreateTime");
                        return (Criteria) this;
                }

                public Criteria andModelCreateTimeGreaterThan(Date value)
                {
                        addCriterion("MODEL_CREATE_TIME >", value, "modelCreateTime");
                        return (Criteria) this;
                }

                public Criteria andModelCreateTimeGreaterThanOrEqualTo(Date value)
                {
                        addCriterion("MODEL_CREATE_TIME >=", value, "modelCreateTime");
                        return (Criteria) this;
                }

                public Criteria andModelCreateTimeLessThan(Date value)
                {
                        addCriterion("MODEL_CREATE_TIME <", value, "modelCreateTime");
                        return (Criteria) this;
                }

                public Criteria andModelCreateTimeLessThanOrEqualTo(Date value)
                {
                        addCriterion("MODEL_CREATE_TIME <=", value, "modelCreateTime");
                        return (Criteria) this;
                }
                

                public Criteria andModelCreateTimeIn(List<Date> values)
                {
                        addCriterion("MODEL_CREATE_TIME in", values, "modelCreateTime");
                        return (Criteria) this;
                }

                public Criteria andModelCreateTimeNotIn(List<Date> values)
                {
                        addCriterion("MODEL_CREATE_TIME not in", values, "modelCreateTime");
                        return (Criteria) this;
                }

                public Criteria andModelCreateTimeBetween(Date value1, Date value2)
                {
                        addCriterion("MODEL_CREATE_TIME between", value1, value2, "modelCreateTime");
                        return (Criteria) this;
                }

                public Criteria andModelCreateTimeNotBetween(Date value1, Date value2)
                {
                        addCriterion("MODEL_CREATE_TIME not between", value1, value2, "modelCreateTime");
                        return (Criteria) this;
                }
				public Criteria andModelIsDeletedIsNull()
                {
                        addCriterion("MODEL_IS_DELETED is null");
                        return (Criteria) this;
                }

                public Criteria andModelIsDeletedIsNotNull()
                {
                        addCriterion("MODEL_IS_DELETED is not null");
                        return (Criteria) this;
                }

                public Criteria andModelIsDeletedEqualTo(YesOrNo value)
                {
                        addCriterion("MODEL_IS_DELETED =", value, "modelIsDeleted");
                        return (Criteria) this;
                }

                public Criteria andModelIsDeletedNotEqualTo(YesOrNo value)
                {
                        addCriterion("MODEL_IS_DELETED <>", value, "modelIsDeleted");
                        return (Criteria) this;
                }

                public Criteria andModelIsDeletedGreaterThan(YesOrNo value)
                {
                        addCriterion("MODEL_IS_DELETED >", value, "modelIsDeleted");
                        return (Criteria) this;
                }

                public Criteria andModelIsDeletedGreaterThanOrEqualTo(YesOrNo value)
                {
                        addCriterion("MODEL_IS_DELETED >=", value, "modelIsDeleted");
                        return (Criteria) this;
                }

                public Criteria andModelIsDeletedLessThan(YesOrNo value)
                {
                        addCriterion("MODEL_IS_DELETED <", value, "modelIsDeleted");
                        return (Criteria) this;
                }

                public Criteria andModelIsDeletedLessThanOrEqualTo(YesOrNo value)
                {
                        addCriterion("MODEL_IS_DELETED <=", value, "modelIsDeleted");
                        return (Criteria) this;
                }
                

                public Criteria andModelIsDeletedIn(List<YesOrNo> values)
                {
                        addCriterion("MODEL_IS_DELETED in", values, "modelIsDeleted");
                        return (Criteria) this;
                }

                public Criteria andModelIsDeletedNotIn(List<YesOrNo> values)
                {
                        addCriterion("MODEL_IS_DELETED not in", values, "modelIsDeleted");
                        return (Criteria) this;
                }

                public Criteria andModelIsDeletedBetween(YesOrNo value1, YesOrNo value2)
                {
                        addCriterion("MODEL_IS_DELETED between", value1, value2, "modelIsDeleted");
                        return (Criteria) this;
                }

                public Criteria andModelIsDeletedNotBetween(YesOrNo value1, YesOrNo value2)
                {
                        addCriterion("MODEL_IS_DELETED not between", value1, value2, "modelIsDeleted");
                        return (Criteria) this;
                }
				public Criteria andModelDeleteTimeIsNull()
                {
                        addCriterion("MODEL_DELETE_TIME is null");
                        return (Criteria) this;
                }

                public Criteria andModelDeleteTimeIsNotNull()
                {
                        addCriterion("MODEL_DELETE_TIME is not null");
                        return (Criteria) this;
                }

                public Criteria andModelDeleteTimeEqualTo(Date value)
                {
                        addCriterion("MODEL_DELETE_TIME =", value, "modelDeleteTime");
                        return (Criteria) this;
                }

                public Criteria andModelDeleteTimeNotEqualTo(Date value)
                {
                        addCriterion("MODEL_DELETE_TIME <>", value, "modelDeleteTime");
                        return (Criteria) this;
                }

                public Criteria andModelDeleteTimeGreaterThan(Date value)
                {
                        addCriterion("MODEL_DELETE_TIME >", value, "modelDeleteTime");
                        return (Criteria) this;
                }

                public Criteria andModelDeleteTimeGreaterThanOrEqualTo(Date value)
                {
                        addCriterion("MODEL_DELETE_TIME >=", value, "modelDeleteTime");
                        return (Criteria) this;
                }

                public Criteria andModelDeleteTimeLessThan(Date value)
                {
                        addCriterion("MODEL_DELETE_TIME <", value, "modelDeleteTime");
                        return (Criteria) this;
                }

                public Criteria andModelDeleteTimeLessThanOrEqualTo(Date value)
                {
                        addCriterion("MODEL_DELETE_TIME <=", value, "modelDeleteTime");
                        return (Criteria) this;
                }
                

                public Criteria andModelDeleteTimeIn(List<Date> values)
                {
                        addCriterion("MODEL_DELETE_TIME in", values, "modelDeleteTime");
                        return (Criteria) this;
                }

                public Criteria andModelDeleteTimeNotIn(List<Date> values)
                {
                        addCriterion("MODEL_DELETE_TIME not in", values, "modelDeleteTime");
                        return (Criteria) this;
                }

                public Criteria andModelDeleteTimeBetween(Date value1, Date value2)
                {
                        addCriterion("MODEL_DELETE_TIME between", value1, value2, "modelDeleteTime");
                        return (Criteria) this;
                }

                public Criteria andModelDeleteTimeNotBetween(Date value1, Date value2)
                {
                        addCriterion("MODEL_DELETE_TIME not between", value1, value2, "modelDeleteTime");
                        return (Criteria) this;
                }
        }

        /**
         * This class was generated by MyBatis Generator. This class corresponds
         * to the database table MESSAGE
         *
         * @mbggenerated do_not_delete_during_merge Tue Jan 07 14:51:59 CST 2014
         */
        public static class Criteria extends GeneratedCriteria
        {

                protected Criteria()
                {
                        super();
                }
        }

        /**
         * This class was generated by MyBatis Generator. This class corresponds
         * to the database table MESSAGE
         *
         * @mbggenerated Tue Jan 07 14:51:59 CST 2014
         */
        public static class Criterion
        {
                private String condition;

                private Object value;

                private Object secondValue;

                private boolean noValue;

                private boolean singleValue;

                private boolean betweenValue;

                private boolean listValue;

                private String typeHandler;

                public String getCondition()
                {
                        return condition;
                }

                public Object getValue()
                {
                        return value;
                }

                public Object getSecondValue()
                {
                        return secondValue;
                }

                public boolean isNoValue()
                {
                        return noValue;
                }

                public boolean isSingleValue()
                {
                        return singleValue;
                }

                public boolean isBetweenValue()
                {
                        return betweenValue;
                }

                public boolean isListValue()
                {
                        return listValue;
                }

                public String getTypeHandler()
                {
                        return typeHandler;
                }

                protected Criterion(String condition)
                {
                        super();
                        this.condition = condition;
                        this.typeHandler = null;
                        this.noValue = true;
                }

                protected Criterion(String condition, Object value, String typeHandler)
                {
                        super();
                        this.condition = condition;
                        this.value = value;
                        this.typeHandler = typeHandler;
                        if (value instanceof List<?>)
                        {
                                this.listValue = true;
                        } else
                        {
                                this.singleValue = true;
                        }
                }

                protected Criterion(String condition, Object value)
                {
                        this(condition, value, null);
                }

                protected Criterion(String condition, Object value, Object secondValue,
                                String typeHandler)
                {
                        super();
                        this.condition = condition;
                        this.value = value;
                        this.secondValue = secondValue;
                        this.typeHandler = typeHandler;
                        this.betweenValue = true;
                }

                protected Criterion(String condition, Object value, Object secondValue)
                {
                        this(condition, value, secondValue, null);
                }
        }
}