package com.nbm.core.modeldriven.test.model.dao;

import com.nbm.core.modeldriven.test.model.ModelDrivenTestModel;
import com.nbm.core.modeldriven.test.model.dao.ModelDrivenTestModelExample;
import com.nbm.waf.core.modeldriven.Mapper;

/**
 * auto generated by nbm-dbgenerator at 2016-5-11 10:11:50
 */
public interface ModelDrivenTestModelMapper extends Mapper<ModelDrivenTestModel, ModelDrivenTestModelExample>
{
}