package com.nbm.core.modeldriven.h2.test.dao;

import com.nbm.core.modeldriven.h2.test.TestModelOracle;
import com.nbm.core.modeldriven.h2.test.dao.TestModelOracleExample;
import com.nbm.waf.core.modeldriven.Mapper;

/**
 * auto generated by nbm-dbgenerator at 2016-4-16 11:26:01
 */
public interface TestModelOracleMapper extends Mapper<TestModelOracle, TestModelOracleExample>
{
}