
package com.nbm.core.modeldriven.h2.test.dao;

import com.nbm.core.modeldriven.h2.test.TestModelMysql;
import com.nbm.core.modeldriven.h2.test.dao.TestModelMysqlExample;
import com.nbm.waf.core.modeldriven.Mapper;

/**
 * auto generated by nbm-dbgenerator at 2016-4-16 10:55:07
 */
public interface TestModelMysqlMapper extends Mapper<TestModelMysql, TestModelMysqlExample>
{
}