-- auto generated by nbm-dbgenerator at May 16, 2017 3:03:10 PM

CREATE TABLE `COMMON_DAO_TEST_MODEL`
(
	`ID` BIGINT unsigned AUTO_INCREMENT,
	`NAME` VARCHAR(200) ,
	`AGE` BIGINT ,
	PRIMARY KEY (`ID`)
) ;