package com.wayeasoft.waf.core.sec.model;

import com.nbm.core.modeldriven.Model;
import com.nbm.core.modeldriven.anno.ModelInfo;

@ModelInfo(tableName = "S_ROLE_PERMIT")
public class RolePermit extends Model
{
        /**
         * 
         */
        private static final long serialVersionUID = 1L;


        private Long roleId;

        private Long moduleitemId;


        /**
         * This method was generated by MyBatis Generator. This method returns
         * the value of the database column S_ROLE_PERMIT.ROLE_ID
         *
         * @return the value of S_ROLE_PERMIT.ROLE_ID
         *
         * @mbggenerated Thu Aug 08 15:08:51 CST 2013
         */
        public Long getRoleId()
        {
                return roleId;
        }

        public void setRoleId(Long roleId)
        {
                this.roleId = roleId;
        }

        public Long getModuleitemId()
        {
                return moduleitemId;
        }

        public void setModuleitemId(Long moduleitemId)
        {
                this.moduleitemId = moduleitemId;
        }
}