
package com.wayeasoft.waf.demo.dao;

import com.wayeasoft.waf.demo.DemoModel;
import com.wayeasoft.waf.demo.dao.DemoModelExample;
import com.nbm.waf.core.modeldriven.Mapper;

/**
 * auto generated by nbm-dbgenerator at Jun 1, 2017 10:40:16 AM
 */
public interface DemoModelMapper extends Mapper<DemoModel, DemoModelExample>
{
}